cc_test(
    name = "gpio_test",
    srcs = ["gpio_test.cc"],
    copts = [],
    deps = [
        "//supruglue/test32",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "soc_test",
    srcs = ["soc_test.cc"],
#    copts = ["-Isupruglue/test32"],
    deps = [
        "//supruglue/test32",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "pinmap_test",
    srcs = ["pinmap_test.cc"],
#    copts = ["-Isupruglue/test32"],
    deps = [
        "//supruglue/test32",
        "@gtest//:gtest_main",
    ],
)
