FROM debian:bullseye-slim

RUN apt-get -y update
RUN apt-get -y install gcc-arm-linux-gnueabihf
RUN apt-get -y install git
RUN apt-get -y install cpio
RUN apt-get -y install lz4
RUN apt-get -y install bc
RUN apt-get -y install build-essential
RUN apt-get -y install fakeroot
RUN apt-get -y install lsb-release
RUN apt-get -y install lzma
RUN apt-get -y install man-db
RUN apt-get -y install gettext
RUN apt-get -y install bison
RUN apt-get -y install flex
RUN apt-get -y install pkg-config
RUN apt-get -y install libmpc-dev
RUN apt-get -y install u-boot-tools
RUN apt-get -y install libncurses-dev:amd64
RUN apt-get -y install libssl-dev:amd64
RUN apt-get -y install wget
