#!/bin/bash -e
#
# Tier 2 fallback: run a RobertCNelson/bb-kernel build script against a scratch
# copy of the pinned kernel/bb-kernel submodule. The submodule is never
# modified; sources are synced into kernel/.kernel-build (which also persists
# the downloaded Linux source and ccache between runs).
#
# Invoked inside the container by ../make.sh, with the kernel directory mounted
# at /work. $1 is the bb-kernel script to run (e.g. ./build_deb.sh).

SCRIPT="${1:-./build_deb.sh}"

WORK=/work
SRC="${WORK}/bb-kernel"
SCRATCH="${WORK}/.kernel-build"

if [ ! -f "${SRC}/build_deb.sh" ]; then
  echo "error: ${SRC} missing; run: git submodule update --init kernel/bb-kernel" >&2
  exit 1
fi

mkdir -p "${SCRATCH}"

# Sync the build scripts/patches without deleting cached downloads or KERNEL/.
rsync -a --exclude='.git' "${SRC}/" "${SCRATCH}/"

# Non-interactive build configuration. Written into the scratch copy only.
cat > "${SCRATCH}/system.sh" <<'EOF'
# Generated by kernel/docker/run.sh - do not edit.
AUTO_BUILD=1
CC=arm-linux-gnueabihf-
EOF

echo "Running ${SCRIPT} in ${SCRATCH}"
cd "${SCRATCH}"
${SCRIPT}
echo "Exited: $?"
echo "Artifacts (if any) are under kernel/.kernel-build/deploy/"
