# -*- Mode: Python -*-
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "debug",
    srcs = [
	"debug.c",
    ],
    hdrs = [
        "debug.h",
    ],
    deps = [
        "//lib/soc",
        "//lib/pinmap",
        "//lib/gpio",
    ],
)
