# -*- Mode: Python -*-
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "test32",
    hdrs = [
        "soc.h",
    ],
    deps = [
        "//supruglue",
        "//tools/toolchain/am335x:incompatible",
        "@ti-pru-support//include",
    ],
)
