# -*- Mode: Python -*-
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "am335x",
    srcs = [
        "dma-am335x.c",
    ],
    hdrs = [
        "dma-am335x.h",
    ],
    deps = [
        "//lib/dma:defs",
        "//tools/toolchain/am335x",
    ],
)
