# -*- Mode: Python -*-
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "test32",
    srcs = [
        # "intc.cc",
    ],
    hdrs = [
        "intc.h",
    ],
    deps = [
        "//lib/intc:defs",
    ],
)

# cc_test(
#     name = "intc_test",
#     srcs = ["intc_test.cc"],
#     deps = [
#         "//lib/intc",
#         "@com_google_googletest//:gtest_main",
#     ],
# )
