# -*- Mode: Python -*-
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "test32",
    srcs = [
        "intc.cc",
    ],
    hdrs = [
        "intc.h",
    ],
    deps = [
        "@com_google_absl//absl/log",
        "//lib/intc:defs",
    ],
)
