# -*- Mode: Python -*-
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "am335x",
    hdrs = [
        "period-am335x.h",
    ],
    srcs = [
        "period-am335x.c",
    ],
    deps = [
        "//lib/thread",
        "//lib/time/period:defs",
        "//tools/toolchain/am335x",
    ],
)
