# -*- Mode: Python -*-
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "am335x",
    hdrs = [
        "gpio.h",
    ],
    srcs = [
        "gpio.c",
    ],
    deps = [
        "//lib/gpio:defs",
    ],
)
