package main

import (
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/jmacd/supruglue/tools/internal/arch"
	"github.com/jmacd/supruglue/tools/internal/csv"
	"github.com/mitchellh/mapstructure"
	yaml "gopkg.in/yaml.v3"
)

func main() {
	if len(os.Args) != 3 {
		log.Fatal("usage: %s <sysevts.csv> <irqconfig.yaml>\n", os.Args[0])
	}
	sevts, err := csv.ReadFile[arch.SystemEvent](os.Args[1])
	sysevtMap := arch.SystemEventMap(sevts)

	obj := map[string]interface{}{}

	data, err := os.ReadFile(os.Args[2])
	if err != nil {
		log.Fatalf("read yaml #%v\n", err)
	}
	err = yaml.Unmarshal(data, obj)
	if err != nil {
		log.Fatalf("unmarshal yaml: %v\n", err)
	}
	var result arch.IRQs
	dec, err := mapstructure.NewDecoder(&mapstructure.DecoderConfig{
		ErrorUnused: true,
		Result:      &result,
	})
	if err != nil {
		log.Fatalf("decode yaml #%v\n", err)
	}
	err = dec.Decode(obj)
	if err != nil {
		log.Fatalf("decode yaml #%v\n", err)
	}

	for i := range result.Incoming {
		_, ok := sysevtMap[result.Incoming[i].Event]
		if !ok {
			log.Fatalf("cannot find system event %s\n", result.Incoming[i].Event)
		}
	}

	guard := strings.ToUpper("supruglue_include_irqgen_h")

	fmt.Printf(`// Copyright Joshua MacDonald
// SPDX-License-Identifier: MIT

// Auto-generated by supruglue/tools/cmd/irqgen from supruglue/%s.

#ifndef %s
#define %s

#include <stdint.h>
#include "external/ti-pru-support/include/pru_types.h"
#include "supruglue/sysevts-arch.h"

#pragma DATA_SECTION(supruglue_incoming_irq_rsc, ".pru_irq_map")
#pragma RETAIN(supruglue_incoming_irq_rsc)

// This is a list of interrupts going to the PRU.
struct pru_irq_rsc supruglue_incoming_irq_rsc = {
  0, // type
  %d, // number of entries
%s};

#endif // %s
`, os.Args[2], guard, guard, len(result.Incoming), func() string {
		var sb strings.Builder
		for _, irq := range result.Incoming {
			sb.WriteString("  { ")
			sb.WriteString(irq.Event)
			sb.WriteString(", ")
			sb.WriteString(fmt.Sprint(irq.Channel))
			sb.WriteString(", ")
			sb.WriteString(fmt.Sprint(irq.Host))
			sb.WriteString("},\n")
		}
		return sb.String()
	}(), guard)
}
