load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "csv",
    srcs = ["read.go"],
    importpath = "github.com/jmacd/supruglue/tools/internal/csv",
    visibility = ["//tools:__subpackages__"],
)
