# -*- Mode: Python -*-
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "initproc",
    srcs = [
        "initproc.c",
    ],
    hdrs = [
        "initproc.h",
    ],
    deps = [
        "//lib/debug",
        "//lib/intc",
        "//lib/rpmsg",
        "//lib/time",
        "//lib/coroutine",
        "//lib/log/journal",
    ],
)
