#include "lib/soc/sysevts.h"
#include "gtest/gtest.h"

TEST(SocTest, SysEvts) {
  EXPECT_EQ(16, SYSEVT_PR1_PRU_MST_INTR0_INTR_REQ);
  EXPECT_EQ(17, SYSEVT_PR1_PRU_MST_INTR1_INTR_REQ);
  EXPECT_EQ(18, SYSEVT_PR1_PRU_MST_INTR2_INTR_REQ);
  EXPECT_EQ(19, SYSEVT_PR1_PRU_MST_INTR3_INTR_REQ);
}
