# -*- Mode: Python -*-
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "test32",
    srcs = [
        "clock-test32.cc",
    ],
    hdrs = [
        "clock-test32.h",
    ],
    deps = [
        "//lib/thread",
        "//lib/intc",
        "//lib/time/clock:defs",
    ],
)
