load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "elfdata",
    srcs = ["elfdata.go"],
    importpath = "github.com/jmacd/supruglue/tools/internal/elfdata",
    visibility = ["//tools:__subpackages__"],
)
