# -*- Mode: Python -*-
package(default_visibility = ["//visibility:public"])

filegroup(
    name = "pins",
    srcs = [
        "bbb-am335x-pins.csv",
    ],
)

filegroup(
    name = "sysevts",
    srcs = [
        "ti-pruss-intr.csv",
    ],
)
