load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "fwstate",
    srcs = ["fwstate.go"],
    importpath = "github.com/jmacd/supruglue/tools/internal/fwstate",
    visibility = ["//tools:__subpackages__"],
)
