# -*- Mode: Python -*-
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "sync",
    srcs = [
        "sync.c",
    ],
    hdrs = [
        "sync.h",
    ],
    deps = [
        "//lib/thread",
    ],
)

# cc_test(
#     name = "test",
#     srcs = ["sync_test.cc"],
#     deps = [
#         ":sync",
#         "@com_google_googletest//:gtest_main",
#     ],
# )
