#!/bin/bash
ARGS=
for x in $@; do
    if [ "$x" = "rcsD" ]; then
	ARGS="${ARGS}"
    else
	ARGS="${ARGS} ${x}"
    fi
done
echo Running external/ti-cgt-pru/bin/arpru ${ARGS}
exec external/ti-cgt-pru/bin/arpru $@
