#!/bin/bash
ARGS=
CMD=clpru

if [ "$1" = "-o" ]; then
    CMD=lnkpru
fi

>&2 echo "CLPRU: PWD=\"$(pwd)\"; PATH=\"${PATH}\" ARG1=\"$1\" ARG2=\"$2\" CMD=$CMD"

for x in $@; do
    echo ARG $x
    if [ "$x" = "-c" ]; then
	ARGS="${ARGS} -c"
    elif [ "$x" = "-o" ]; then
	if [ "${CMD}" = "clpru" ]; then
	    ARGS="${ARGS} -fe"
	else
	    ARGS="${ARGS} -o"
	fi
    elif [[ $x =~ \.a$ ]]; then
	ARGS="${ARGS} --library=${x}"
    else
	ARGS="${ARGS} ${x}"
    fi
done

echo Running external/ti-cgt-pru/bin/${CMD} ${ARGS}
exec external/ti-cgt-pru/bin/${CMD} ${ARGS}
