# -*- Mode: Python -*-
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "am335x",
    hdrs = [
        "cap-am335x.h",
    ],
    srcs = [
        "cap-am335x.c",
    ],
    deps = [
        "//lib/cap:defs",
        "//tools/toolchain/am335x",
    ],
)
