load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "am335x",
    srcs = ["module.go"],
    importpath = "github.com/jmacd/supruglue/tools/internal/memorymap/am335x",
    visibility = ["//tools:__subpackages__"],
)
