#!/bin/bash
ARGS=
for x in $@; do
    if [ "$x" = "rcsD" ]; then
	ARGS="${ARGS} rs0"
    else
	ARGS="${ARGS} ${x}"
    fi
done
#echo Running ${TI_CGT_PRU_ROOT}/bin/arpru ${ARGS}
exec ${TI_CGT_PRU_ROOT}/bin/arpru ${ARGS}
