load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "memorymap",
    srcs = ["memorymap.go"],
    importpath = "github.com/jmacd/supruglue/tools/internal/memorymap",
    visibility = ["//tools:__subpackages__"],
)
