# -*- Mode: Python -*-
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "am335x",
    hdrs = [
        "intc.h",
    ],
    srcs = [
        "intc.c",
    ],
    deps = [
        "//lib/intc:defs",
        "//lib/debug",
    ],
)
